#!/usr/bin/env node
/**
 * Firebase Functions deploy only bundles the "functions" source directory
 * (firebase.json: functions[0].source === "functions") - nothing outside
 * it is uploaded, so functions/index.js can't require("../shared/...")
 * or require("../scripts/...") in a deployed function (those paths simply
 * won't exist in the deployed container). Phase C4 (DeletionImplementation.md)
 * needs functions/index.js's scheduled cleanup job to call the REAL C3
 * hard-delete engine (scripts/runSpaceMigration.js's hardDeleteAreaAdmin/
 * hardDeleteRoomAdmin), not a second implementation - so this script
 * copies the two files it depends on into functions/, preserving the
 * exact same relative directory shape (functions/scripts/ ->
 * functions/shared/, mirroring scripts/ -> shared/ at the repo root) so
 * the copied runSpaceMigration.js's own `require("../shared/spaceMigration")`
 * resolves correctly with zero changes to its contents - a byte-for-byte
 * copy, not a transcription, so nothing can drift by manual-copy error.
 *
 * Runs automatically before every `firebase deploy --only functions`
 * (firebase.json's functions[0].predeploy hook). Also safe/idempotent to
 * run manually any time (local testing, before committing) - it always
 * copies fresh from the canonical source (shared/spaceMigration.js,
 * scripts/runSpaceMigration.js), never the reverse.
 *
 * The copied files ARE committed to git (not .gitignore'd) so a clone
 * always has a deployable functions/ directory even if a deploy is ever
 * triggered without this predeploy hook firing - but they are generated,
 * never hand-edited. If `git diff` ever shows functions/shared/ or
 * functions/scripts/ changing without the corresponding root-level
 * shared/ or scripts/ file changing in the same commit, something wrote
 * to the wrong copy - fix the root-level source and rerun this script.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const COPIES = [
  { from: path.join(ROOT, "shared", "spaceMigration.js"), to: path.join(ROOT, "functions", "shared", "spaceMigration.js") },
  // spaceMigration.js's own sibling dependency (require("./spaceShadowValidation")) -
  // must travel with it or the copy fails to load at all.
  { from: path.join(ROOT, "shared", "spaceShadowValidation.js"), to: path.join(ROOT, "functions", "shared", "spaceShadowValidation.js") },
  { from: path.join(ROOT, "scripts", "runSpaceMigration.js"), to: path.join(ROOT, "functions", "scripts", "runSpaceMigration.js") },
];

const GENERATED_HEADER = "// GENERATED FILE - do not hand-edit. Regenerated by scripts/prepareFunctionsDeploy.js\n" +
  "// (also runs automatically before every `firebase deploy --only functions`).\n" +
  "// Canonical source: ";

for (const { from, to } of COPIES) {
  let contents = fs.readFileSync(from, "utf8");
  const relSource = path.relative(ROOT, from).replace(/\\/g, "/");
  // A leading "#!" hashbang is only special-cased by Node when it's the
  // literal first line of the file - inserting our own header above it
  // would turn it into a syntax error. Preserve it as the true first line
  // when present; insert the generated-file header right after instead.
  let shebangLine = "";
  if (contents.startsWith("#!")) {
    const newlineIdx = contents.indexOf("\n");
    shebangLine = contents.slice(0, newlineIdx + 1);
    contents = contents.slice(newlineIdx + 1);
  }
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.writeFileSync(to, shebangLine + GENERATED_HEADER + relSource + "\n" + contents);
  console.log(`Copied ${relSource} -> ${path.relative(ROOT, to).replace(/\\/g, "/")}`);
}
